export const Routes = {
  dashboard: '/',
  login: '/login',
  logout: '/logout',
  settings: '/settings',
  services: '/services',
  airports: '/airports',
  lastmileprovider: '/last-mile-provider',
  brokers: '/brokers',
  customers: '/customers',
  commodity_mapping: '/cm',
  description_list: '/description-list',
  manifest_upload: '/manifest-upload',
  express_upload: '/express-manifest-upload',
  manifest_list: '/manifest-list',
  uld: '/uld',
};
