export const Routes = {
  dashboard: '/',
  login: '/login',
  logout: '/logout',
  settings: '/settings',
  services: '/services',
  airports: '/airports',
  brokers: '/brokers',
  customers: '/customers',
  commodity_mapping:'/cm',
  manifest_upload:'/manifest-upload',
  express_upload:'/express-manifest-upload',
  manifest_list:'/manifest-list',
  uld:'/uld',
}
